### PR TITLE
Create guildwars2.rules

### PR DESCRIPTION
**Pull request by Technetium1**
Tested for both Wine and Steam versions.

### CODE REVIEW

**Comment by Technetium1** [comment]
OMG IT ALREADY EXISTS! I thought I looked hard enough for it first, suppose not..

**Comment by kuche1** [comment]
I think it makes sense to move GW2 over to the games folder. I have merged a new patch for that.

**Comment by Technetium1** [comment]
@kuche1 I would be happy to see wine in games subfolder if wine really must be seperate.

**Comment by kuche1** [comment]
I think getting rid of the wine folder is a good idea.

**Pull request closed without merging**
